#spring.application.name=shop2
server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**  
  
        
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study-0223.cvkw2gims0tm.ap-northeast-2.rds.amazonaws.com:3306/study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: salinza3785sain!
    
mybatis:
  mapper-locations:
  - /mappers/*.xml